#!/bin/bash

#wallpaper fetcher and wallpaper rotator
#type "var" in a terminal to change settings - example
#variety &

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Launch event listener (hypr-rs)
$HOME/.config/hypr/hypr-rs/target/release/hypr-rs event &

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
# ${SCRIPTSDIR}/statusbar &
$HOME/.config/eww/bar/launch_bar &

# Launch nm-applet
nm-applet &

# Xauthority
${SCRIPTSDIR}/xauthority &

# dex $HOME/.config/autostart/arcolinux-welcome-app.desktop &

#insync start &
#dropbox &
#telegram-desktop &
#discord &
#nm-applet --indicator
