[package]
name = "hypr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyprland = "*"
tokio = "*"
serde = "*"
serde_json = "*"
fs2 = "*"
daemonize = "*"
zbus = "*"


