#! /bin/sh

fwid=$(bspc query -N -n focused.automatic)
wid=$1
title=$(xtitle "$wid")
receptacle=$(bspc query -N -n ".leaf.!window.local"  | awk NR==1)
#floats=$(bspc query -N -n .local.floating | wc -l)

if bspc query -N -n "@/.!automatic" > /dev/null ; then
    echo "node=@/"
fi

if [ -n "$receptacle" ] > /dev/null ; then
    echo "node=$receptacle"
elif [ -n "$fwid" ] ; then
    leafNum=$(bspc query -N -d -n .leaf | wc -l)
    nodes=$(bspc query -N -d -n .leaf)
    readarray -t nodesarr <<< "$nodes"
    if [ $leafNum -eq 1 ]; then
        echo "split_dir=east"
    else
        bspc node -f ${nodesarr[-1]}
        echo "split_dir=south"
    fi

fi
#window-placer $floats $wid
